"""intent_id -> Telegram message_id for the open progress/sol_progress chain (m4-progress-edit-in-place-20260916).

Why this lives here and not in core: AC-07 (PATCHNOTES/m4-ac07-full-core-interface-boundary-20260916.md) moved
HTML rendering out of core into interface.presenter, on the principle that core does not depend on Telegram.
A Telegram message_id is exactly that kind of transport detail, so the intent_id -> message_id map belongs in
the interface process — the only process that ever calls the Telegram API and learns a message_id — not in
core. Core is unchanged by this: it still just emits an execution_notice DTO carrying intent_id as one fact
among others, same as before; interface.presenter.present() is what consults this tracker to turn a repeat
progress/sol_progress notice for the same intent_id into an edit of the previous message instead of a new send.

This mirrors a mechanism that already existed twice in this codebase, both keyed by intent_id in a plain
in-memory dict:
  - core/commands.py / tg/bot.py: Bot._progress / Bot._progress_pending (the pre-DTO throttle/edit path,
    Bot.progress()) — still reachable today only through tg/bot.py's single-process BotHooks.notice(), which
    special-cases topic in ('progress', 'sol_progress') to call Bot.progress(iid, text) instead of Bot.say(text).
    In the split core/interface architecture (core/commands.py's own BotHooks.notice -> Bot.execution_notice
    -> Outbox -> execution_notice DTO) that special-casing was never ported over: every stage became a new
    'send'. That gap is what this module and the routing in interface/presenter.py close.
  - core/journal.py: Outbox.plan_proposed/plan_closed already hoist a routing key (plan_id) next to an opaque
    DTO so the *notification* delivery layer (Journal.acknowledge) can bind a learned message_id back to the
    right intents row without decoding the payload. Same idea, different owner: plan message_id is a durable,
    core-visible fact (a plan can be approved after a restart, so it is persisted in trade.db against the
    intent), while a progress message_id is not — see below.

In-memory only, not persisted. This is a deliberate continuation of the precedent above (Bot._progress was
also only ever a plain dict on the core process, lost on a core restart) rather than a new decision — see
PATCHNOTES/m4-progress-edit-in-place-20260916.md for the reasoning and what it means across an interface
restart: the next progress/sol_progress notice for an intent_id interface no longer remembers starts a fresh
message. That is always safe (never edits a stale/wrong message) because intent_id is generated by
trade/store.py: new_id() checked against the full, append-only `intents` table — it is never reused.
"""
import threading

# A healthy bot has at most one open progress chain: trade/engine.py: Engine.run() executes intents one at a
# time off a single queue (store.approve_intent's compare-and-set also refuses a second concurrent execution
# with StoreBusy — belt and suspenders at two layers), so a second intent_id's progress/sol_progress notice
# can only start after the previous run's execute() has returned. This bound is just a safety net against
# unbounded growth if that invariant is ever wrong or a terminal notice is ever missed — not load-bearing for
# correctness (see forget() and the module docstring).
MAX_TRACKED = 32


class ProgressTracker:
    """Not persisted; safe to use from multiple threads (interface/runtime.py calls route()/forget() from the
    notification-delivery thread and resolved() from the Telegram sender's own worker thread)."""

    def __init__(self, max_tracked: int = MAX_TRACKED):
        self._lock = threading.Lock()
        self._message_id: dict[str, int] = {}          # resolved: intent_id -> message_id
        self._inflight: set[str] = set()                # first send dispatched, message_id not back yet
        self._pending: dict[str, tuple[int, str]] = {}  # intent_id -> latest (chat_id, text) queued while inflight
        self.max_tracked = max_tracked

    def route(self, intent_id: str, chat_id: int, text: str):
        """Call once per progress/sol_progress notice, before delivering it. Returns:
          ('send', None)       — unseen intent_id: caller sends a new message, then must call resolved().
          ('wait', None)       — a send for this intent_id is already in flight (resolved() hasn't fired
                                  yet); this call's text is stashed as the latest and nothing more needs to
                                  happen now — resolved() flushes it as an edit once the message_id is known.
          ('edit', message_id) — caller edits that message in place.
        """
        with self._lock:
            mid = self._message_id.get(intent_id)
            if mid is not None:
                return 'edit', mid
            if intent_id in self._inflight:
                self._pending[intent_id] = (chat_id, text)
                return 'wait', None
            self._inflight.add(intent_id)
            return 'send', None

    def resolved(self, intent_id: str, message_id: int | None):
        """Call once the 'send' dispatched for intent_id comes back from Telegram — message_id is the id it
        was assigned, or None if it was not delivered at all (queue full, all retries exhausted, ...).
        Returns the latest (chat_id, text) queued by route() while the send was in flight, or None — caller
        should deliver a returned pair as a throttled edit of message_id."""
        with self._lock:
            self._inflight.discard(intent_id)
            pending = self._pending.pop(intent_id, None)
            if message_id is None:
                # Never delivered: nothing to edit. Forget it so the next progress notice for this
                # intent_id starts a fresh 'send' rather than targeting a message that was never created;
                # the queued text (if any) is dropped along with it — the next notice supersedes it anyway.
                self._message_id.pop(intent_id, None)
                return None
            self._message_id[intent_id] = message_id
            self._prune_locked()
            return pending

    def forget(self, intent_id: str) -> None:
        """Drop all state for intent_id: its run reached a terminal, non-progress notice (halt, sol_halt,
        executor_crash — see PROGRESS_TERMINAL_TOPICS in interface/presenter.py). Idempotent; safe to call
        for an intent_id that was never tracked (e.g. 'busy'/'executor_crash' for an intent that never
        progressed) or twice (a retried delivery)."""
        with self._lock:
            self._message_id.pop(intent_id, None)
            self._inflight.discard(intent_id)
            self._pending.pop(intent_id, None)

    def _prune_locked(self) -> None:
        while len(self._message_id) > self.max_tracked:
            self._message_id.pop(next(iter(self._message_id)))
